name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.1.4"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: "${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}"
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Ruff lint
        run: poetry run ruff check .

      - name: Black formatting
        run: poetry run black --check .

      - name: Mypy type checks
        run: poetry run mypy src tests

      - name: Pytest
        run: poetry run pytest
